### PR TITLE
Killaura attacks entities 

### PR DESCRIPTION
**Pull request by de-Gamers638**
If i didn't fix all typo's just tell me i will fix them

### CODE REVIEW

**Comment by DisabledMallis** [comment]
Seems pretty good to me! Ill check this out, confirm it works and merge soon.

**Comment by DisabledMallis** [comment]
ok so i fixed the stuff thats missing & why its not compiling, however the game crashes now so lets fix that before merging. (Before the code did nothing cuz the event handler didnt even send out the tick event 😐)

**Comment by DisabledMallis** [comment]
the one from the event is from the player

**Comment by DisabledMallis** [comment]
https://github.com/de-Gamers638/Lunity/blob/3a7c990876b8af78eab1b1540bbce7b5f9daefc6/Lunity/Client/Patches/Player/NormalTickHook.cpp#L7

Look here, the event is created with GameMode being provided from the player. The pointer is the same from the event and the player. For compatibility reasons, it'd probably be wise to use it from the event.

**Comment by DisabledMallis** [comment]
From what I can tell, its the actual GM->Attack call thats causing the crash. Im going to take a deeper look into this.

**Comment by de-Gamers638** [comment]
Hmm maybe it's not the right param's

**Comment by de-Gamers638** [comment]
Or the attack one needs to be a void instead of a bool

**Comment by de-Gamers638** [comment]
Maybe this was the issue ^^

**Pull request closed without merging**
