### PR TITLE
Optimised ModuleTick & Updated Vector Class + Color Class

### PR DESCRIPTION
**Pull request by CXCubeHD**

### CODE REVIEW

**Comment by DisabledMallis** [comment]
I appreciate the effort, and good thing you pointed out that missing Sleep call, ill make sure to merge that.
However: the vector class changes are a lot of work to save a few keystrokes. I wont merge those changes because
1. Code readability - what was proposed makes reading the code more difficult even though it is less to type.
2. The shortened names should be macros - renaming the entire type and refactoring it to 'Vec3F' was a change that could have been made with a simple `#define` directive. I don't feel this is a necessary change.

Let me know what you think

**Comment by CXCubeHD** [comment]
Thank you for the deedback. I think I might change ``Vec`` to ``Vector`` to increase readability. Also I would like to point out that you should try to not use ``#define`` but rather ``typedef`` or ``using`` instead. Use ``#define`` only when really needed. I guess I will then just change ``Vec`` to ``Vector``.

Tell me what you think about the ``Color`` class.

**Comment by DisabledMallis** [comment]
Forgot to respond. So sorry. I like the color class, I think overall its a good helpful class for us. Ill definately start using that.

**Comment by CXCubeHD** [comment]
Gonna close this, cause I will make a new fork

**Pull request closed without merging**
