### PR TITLE
Updated Vector class added ImGuiD3D12Renderer

### PR DESCRIPTION
**Pull request by CXCubeHD**
(full implementation needs to be done)

### CODE REVIEW

**Comment by CXCubeHD** [comment]
@DisabledMallis would be the current ImGuiD3D12Renderer implementation okay, or doesn't it fit into the current system?

**Comment by DisabledMallis** [comment]
Theres a lot of good and bad about this PR:

Heres what's good:
- Good renderer, I assume it draws ImGui as expected
- Lots of nice quality-of-life features, especially in terms of maths

Heres what's bad (Why I can't merge):
- Submodules aren't properly added. You didn't need to add them anyway if you just based your changes on the Dx11-Hook branch. I cannot merge unless this is resolved because I fear there will be many issues later on from it.
- Doesn't use the Patch system *properly*. Patches are supposed to be just hooks and minimal other features. For example, the patch should hook just present, then call the Renderer and handle the hooked function there. **The renderer should not be the patch**!!!

Other things i noticed (Not as important, to be fair. I'll probably still merge if you don't address this)
- No simple way to simply draw text and shapes (No simple renderer feature, only the ImGui one afaik)

Please fix the issues I mention. Once fixed, I'll merge.

**Please move your changes to the Dx11-Hook branch!!!**

**Comment by CXCubeHD** [comment]
I will move it to another branch. I just don't really understand how I am supposed to work with patches? Could you give some examples how I am supposed to work with it in this scenario?
(Also shapes are being drawn with ImGui, as of for now)

**Comment by CXCubeHD** [comment]
Also why are those submodules wrongly implemented, this seems fine to me?

**Comment by LunityClient** [comment]
> I will move it to another branch. I just don't really understand how I am supposed to work with patches? Could you give some examples how I am supposed to work with it in this scenario?
> (Also shapes are being drawn with ImGui, as of for now)

You can use my Dx11 present patch as an example. There is also the ClientInstance patch that uses polyhook to retrieve the ClientInstance*.



> Also why are those submodules wrongly implemented, this seems fine to me? Is CMake the reason?

Might've just been my end, but I had some issues with your submodules. When adding submodules, make sure they are added with the "git submodule" command properly

**Comment by CXCubeHD** [comment]
well going to restructure it :)

also submodules seem fine to me:

**Comment by DisabledMallis** [comment]
I manually merged this to the Dx11-Hook branch. I'll merge the pull request when the feature is complete.

**Comment by CXCubeHD** [comment]
> I manually merged this to the Dx11-Hook branch. I'll merge the pull request when the feature is complete.
> 
> EDIT: Also does this render anything to the screen yet? I built and injected it with no visible UI or anything...

not yet but I am working on it

**Comment by DisabledMallis** [comment]
> > I manually merged this to the Dx11-Hook branch. I'll merge the pull request when the feature is complete.
> > EDIT: Also does this render anything to the screen yet? I built and injected it with no visible UI or anything...
> 
> not yet but I am working on it, but soon it will be functional, also I am working on a new and advanced rendering system which will allow us to animate our gui even better

Sounds good 👌

**Review by DisabledMallis — COMMENTED** [review]
Could we discuss the Event class? I feel like we should not have a C# event system, but rather a "Bukkit"-like event system. This would be used in hooks and such to simplify modules in an easy-to-read form.

**Comment by CXCubeHD** [comment]
> Could we discuss the Event class? I feel like we should not have a C# event system, but rather a "Bukkit"-like event system. This would be used in hooks and such to simplify modules in an easy-to-read form.

Idk, but if you say so...

**Comment by DisabledMallis** [comment]
On the topic of rendering, this is probably being really picky, but if possible can we have an implementation of https://github.com/LunityClient/Lunity/blob/Dx11-Hook/Lunity/Utils/Renderer.h for the renderer? The header isn't complete, BUT it would server as an amazing baseline. Idk, do what you think is best but I think having a renderer like in my header would be best since its simple & flexible, at least for use.

**Comment by moveq5** [comment]
image

Using two hooking libraries is bloating the binary and dumb. [kiero::bind](https://github.com/Rebzzel/kiero/blob/35d4e4f7510f9123646f759beede172d22a85650/kiero.cpp#L689) is just a call to mh createhook, define KIERO_USE_MINHOOK as 0 and use PolyHook instead.

Better yet, remove kiero entirely because its a small amount of code not deserving of an entire submodule.

**Comment by DisabledMallis** [comment]
You're right, pretty sure CXCube's hook doesnt use it? I think only my hook used it and that will 99% get scrapped anyway.

**Pull request closed without merging**
